[package]
authors = ["Ryan Thomas <ryan@ryant.org>"]
edition = "2018"
name = "dms"
version = "0.1.0"

[dependencies]
nom = "6.0.0"
tokio = { version = "0.3.4", features = ["full"] }
tracing = "0.1.21" 

