[package]
name = "dns-message"
version = "0.1.0"
authors = ["Ryan Thomas <ryan@ryant.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.37"
bytes = "1.0.0"
nom = "6.0.1"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
